version: '3.8'

services:
  neo4j:
    image: neo4j:5.26-community
    container_name: podinsight-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/podinsight123  # Change this password!
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - podinsight-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  graphiti-mcp:
    image: python:3.10-slim
    container_name: podinsight-graphiti-mcp
    working_dir: /app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=podinsight123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-4o-mini
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - podinsight-network
    restart: unless-stopped
    volumes:
      - ./simple-mcp-server.py:/app/simple-mcp-server.py
    command: ["python", "/app/simple-mcp-server.py"]

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  graphiti_data:
    driver: local

networks:
  podinsight-network:
    driver: bridge